export const constants = {
	HTTP_STATUS_OK: 200,
	HTTP_STATUS_BAD_REQUEST: 400,
	HTTP_FORBIDDEN: 403,
	HTTP_STATUS_NOT_FOUND: 404,
	HTTP_STATUS_INTERNAL_SERVER_ERROR: 500,
	SP_WORKING_DIR: '/tmp',
};
